export { KAMPF_NACHLAUF_MS, tafelrunde } from './adapter.js';
export {
  type Einheit,
  type EinheitId,
  type Grundwerte,
  type Kosten,
  type Marke,
  type Rolle,
  type Stufe,
  type Wertebonus,
  KATALOG,
  KEIN_BONUS,
  KOSTENSTUFEN,
  MARKEN,
  MAX_STUFE,
  RUESTUNG_HOECHSTWERT,
  STUFEN_FAKTOR,
  VERSCHMELZ_ZAHL,
  VORRAT_JE_KOSTEN,
  einheit,
  einheitenMitKosten,
  gesamtkosten,
  istEinheitId,
  kartenZahl,
  werteFuer,
} from './katalog.js';
export {
  type Hexfeld,
  BRETT_FELDER,
  BRETT_REIHEN,
  BRETT_SPALTEN,
  hexAbstand,
  hexfeld,
  hexNachbarn,
  istBrettplatz,
  platzNummer,
} from './brett.js';
export {
  type Seite,
  ARENA_FELDER,
  ARENA_LUECKE,
  ARENA_REIHEN,
  ARENA_SPALTEN,
  SEITEN,
  arenaAbstand,
  arenaNachbarn,
  gegenseite,
  haelfteVon,
  istArenaplatz,
  nachArena,
  vonArena,
} from './arena.js';
export {
  type Aufgestellt,
  type Brettseite,
  type Endgrund,
  type Ereignis,
  type Kaempferstand,
  type Kampfbericht,
  type Kampfregler,
  HOECHSTDAUER_MS,
  SCHADEN_GRUNDWERT,
  SCHADEN_STUFEN_TEILER,
  SCHRITT_MS,
  STANDARD_REGLER,
  TAKT_MS,
  angriffstakt,
  protokollText,
  schadenFuerVerlierer,
  schadenNach,
  schrittdauer,
  simuliereKampf,
  ueberlebendeVon,
} from './kampf.js';
export {
  type Levelstufe,
  type TafelrundeRegeln,
  DEFAULT_REGELN,
  LEVEL_TABELLE,
  MAX_LEVEL,
  SEAT_COUNTS,
  START_LEVEL,
  ZINS_MAX,
  ZINS_SCHRITT,
  aufstiegKosten,
  feldplaetze,
  ladenChancen,
  levelstufe,
  mitFrist,
  pruefeRegeln,
  serienBonus,
  zins,
} from './regeln.js';
export {
  type Bereich,
  type Heer,
  type Kaempfer,
  type Kampfausgang,
  type Kampfpaarung,
  type Ansetzung,
  type Ort,
  type Phase,
  type TafelrundeAktion,
  type TafelrundePartie,
  type Saat,
  type Serie,
  type Serienart,
  KEINE_SERIE,
  amZug,
  ausgaengeAus,
  baueZufall,
  brettBelegung,
  darfHandeln,
  einkommen,
  erlaubteZuege,
  erstellePartie,
  fristAbgelaufen,
  fuehreAus,
  heerVon,
  istKaempfer,
  kampfSaat,
  kampfVon,
  kampfdauer,
  ladenSaat,
  lebendeSitze,
  lebt,
  loeseKampfAuf,
  markiereVerlassen,
  ohneKampfWeiter,
  paarungsSaat,
  platzierungen,
  setzeAn,
  sieger,
  sitzeVon,
  verschmelze,
  vollerVorrat,
  vorratSumme,
  wendeKampfausgang,
  zieheKarte,
  zieheLaden,
} from './partie.js';
export {
  type EigeneSicht,
  type FremdeSicht,
  type Paarungsergebnis,
  type Platzstand,
  type TafelrundeSicht,
  SICHT_MARKE,
  eigenesLebt,
  sichtFuer,
  zuschauerSicht,
} from './sicht.js';
export {
  type Aufgestellte,
  type Markenzaehlung,
  type Schwelle,
  type Synergie,
  type Synergiestand,
  type Synergiestufe,
  SCHWELLEN,
  SYNERGIEN,
  aktiveSchwelle,
  bonusDerMarke,
  bonusFuerEinheit,
  naechsteSchwelle,
  synergie,
  synergienVon,
  zaehleMarken,
} from './synergien.js';
export { botZug } from './bot.js';
