/**
 * Woerter fuer Imposter.
 *
 * Alle Mitspieler bekommen `wort`, der Imposter den `hinweis` — eine grobe
 * Kategorie, die das Wort nicht verraet. Neue Eintraege werden HINTEN
 * angehaengt, mit der naechsten freien Kennung (`i121`, `i122`, ...).
 * Bestehende Kennungen werden nie umbenannt oder neu vergeben, da sie in
 * abgelegten Rundenprotokollen stehen.
 */

import type { ImposterWort } from '../../src/inhalte/typen.js';

export const IMPOSTER_WOERTER: readonly ImposterWort[] = [
  { id: 'i001', wort: 'Strand', hinweis: 'Ein Ort im Urlaub' },
  { id: 'i002', wort: 'Zahnarzt', hinweis: 'Ein Beruf' },
  { id: 'i003', wort: 'Fahrrad', hinweis: 'Etwas mit Rädern' },
  { id: 'i004', wort: 'Hochzeit', hinweis: 'Eine Feier' },
  { id: 'i005', wort: 'Schwimmbad', hinweis: 'Ein Ort mit Wasser' },
  { id: 'i006', wort: 'Pizza', hinweis: 'Etwas zu essen' },
  { id: 'i007', wort: 'Hund', hinweis: 'Ein Haustier' },
  { id: 'i008', wort: 'Katze', hinweis: 'Ein Haustier' },
  { id: 'i009', wort: 'Kaffee', hinweis: 'Ein heißes Getränk' },
  { id: 'i010', wort: 'Bahnhof', hinweis: 'Ein Ort zum Reisen' },
  { id: 'i011', wort: 'Schule', hinweis: 'Ein Ort zum Lernen' },
  { id: 'i012', wort: 'Lehrer', hinweis: 'Ein Beruf' },
  { id: 'i013', wort: 'Arzt', hinweis: 'Ein Beruf' },
  { id: 'i014', wort: 'Polizist', hinweis: 'Ein Beruf' },
  { id: 'i015', wort: 'Supermarkt', hinweis: 'Ein Ort zum Einkaufen' },
  { id: 'i016', wort: 'Restaurant', hinweis: 'Ein Ort zum Essen' },
  { id: 'i017', wort: 'Kino', hinweis: 'Ein Ort für Unterhaltung' },
  { id: 'i018', wort: 'Fußball', hinweis: 'Eine Sportart' },
  { id: 'i019', wort: 'Tennis', hinweis: 'Eine Sportart' },
  { id: 'i020', wort: 'Skifahren', hinweis: 'Eine Wintersportart' },
  { id: 'i021', wort: 'Kuchen', hinweis: 'Etwas Süßes zum Essen' },
  { id: 'i022', wort: 'Brot', hinweis: 'Etwas zum Essen' },
  { id: 'i023', wort: 'Apfel', hinweis: 'Eine Obstsorte' },
  { id: 'i024', wort: 'Zitrone', hinweis: 'Eine Obstsorte' },
  { id: 'i025', wort: 'Bier', hinweis: 'Ein alkoholisches Getränk' },
  { id: 'i026', wort: 'Whisky', hinweis: 'Ein alkoholisches Getränk' },
  { id: 'i027', wort: 'Zug', hinweis: 'Ein Verkehrsmittel' },
  { id: 'i028', wort: 'Bus', hinweis: 'Ein Verkehrsmittel' },
  { id: 'i029', wort: 'Boot', hinweis: 'Ein Verkehrsmittel auf Wasser' },
  { id: 'i030', wort: 'Flugzeug', hinweis: 'Ein Fluggerät' },
  { id: 'i031', wort: 'Berg', hinweis: 'Etwas in der Natur' },
  { id: 'i032', wort: 'Fluss', hinweis: 'Etwas mit fließendem Wasser' },
  { id: 'i033', wort: 'See', hinweis: 'Ein Ort mit Wasser' },
  { id: 'i034', wort: 'Wald', hinweis: 'Ein Ort mit Bäumen' },
  { id: 'i035', wort: 'Wiese', hinweis: 'Ein grüner Ort' },
  { id: 'i036', wort: 'Regenschirm', hinweis: 'Etwas gegen Regen' },
  { id: 'i037', wort: 'Jacke', hinweis: 'Ein Kleidungsstück' },
  { id: 'i038', wort: 'Hose', hinweis: 'Ein Kleidungsstück' },
  { id: 'i039', wort: 'Schuhe', hinweis: 'Etwas zum Anziehen' },
  { id: 'i040', wort: 'Mütze', hinweis: 'Ein Kleidungsstück' },
  { id: 'i041', wort: 'Handschuhe', hinweis: 'Ein Kleidungsstück' },
  { id: 'i042', wort: 'Sofa', hinweis: 'Ein Möbelstück' },
  { id: 'i043', wort: 'Bett', hinweis: 'Ein Möbelstück' },
  { id: 'i044', wort: 'Tisch', hinweis: 'Ein Möbelstück' },
  { id: 'i045', wort: 'Stuhl', hinweis: 'Ein Möbelstück' },
  { id: 'i046', wort: 'Fenster', hinweis: 'Etwas an einem Haus' },
  { id: 'i047', wort: 'Garten', hinweis: 'Ein Ort im Freien' },
  { id: 'i048', wort: 'Keller', hinweis: 'Ein Raum im Haus' },
  { id: 'i049', wort: 'Küche', hinweis: 'Ein Raum im Haus' },
  { id: 'i050', wort: 'Bäcker', hinweis: 'Ein Beruf' },
  { id: 'i051', wort: 'Metzger', hinweis: 'Ein Beruf' },
  { id: 'i052', wort: 'Koch', hinweis: 'Ein Beruf' },
  { id: 'i053', wort: 'Pilot', hinweis: 'Ein Beruf' },
  { id: 'i054', wort: 'Kapitän', hinweis: 'Ein Beruf' },
  { id: 'i055', wort: 'Feuerwehrmann', hinweis: 'Ein Beruf' },
  { id: 'i056', wort: 'Anwalt', hinweis: 'Ein Beruf' },
  { id: 'i057', wort: 'Priester', hinweis: 'Ein Beruf' },
  { id: 'i058', wort: 'König', hinweis: 'Eine historische Figur' },
  { id: 'i059', wort: 'Ritter', hinweis: 'Eine historische Figur' },
  { id: 'i060', wort: 'Pirat', hinweis: 'Eine Figur aus Geschichten' },
  { id: 'i061', wort: 'Detektiv', hinweis: 'Ein Beruf' },
  { id: 'i062', wort: 'Clown', hinweis: 'Eine Figur bei Feiern' },
  { id: 'i063', wort: 'Tänzer', hinweis: 'Ein Beruf' },
  { id: 'i064', wort: 'Schauspieler', hinweis: 'Ein Beruf' },
  { id: 'i065', wort: 'Fotograf', hinweis: 'Ein Beruf' },
  { id: 'i066', wort: 'Schneider', hinweis: 'Ein Beruf' },
  { id: 'i067', wort: 'Bauer', hinweis: 'Ein Beruf' },
  { id: 'i068', wort: 'Jäger', hinweis: 'Ein Beruf' },
  { id: 'i069', wort: 'Camping', hinweis: 'Eine Urlaubsart' },
  { id: 'i070', wort: 'Kreuzfahrt', hinweis: 'Eine Urlaubsart' },
  { id: 'i071', wort: 'Skiurlaub', hinweis: 'Eine Urlaubsart' },
  { id: 'i072', wort: 'Grillfest', hinweis: 'Eine Feier im Freien' },
  { id: 'i073', wort: 'Geburtstag', hinweis: 'Eine Feier' },
  { id: 'i074', wort: 'Weihnachten', hinweis: 'Ein Fest im Jahr' },
  { id: 'i075', wort: 'Ostern', hinweis: 'Ein Fest im Jahr' },
  { id: 'i076', wort: 'Karneval', hinweis: 'Ein Fest im Jahr' },
  { id: 'i077', wort: 'Konzert', hinweis: 'Eine Veranstaltung mit Musik' },
  { id: 'i078', wort: 'Zirkus', hinweis: 'Eine Veranstaltung mit Unterhaltung' },
  { id: 'i079', wort: 'Museum', hinweis: 'Ein Ort zum Ansehen' },
  { id: 'i080', wort: 'Aquarium', hinweis: 'Ein Ort mit Tieren' },
  { id: 'i081', wort: 'Achterbahn', hinweis: 'Etwas auf dem Rummel' },
  { id: 'i082', wort: 'Schwimmen', hinweis: 'Etwas im Wasser' },
  { id: 'i083', wort: 'Joggen', hinweis: 'Eine sportliche Aktivität' },
  { id: 'i084', wort: 'Yoga', hinweis: 'Eine sportliche Aktivität' },
  { id: 'i085', wort: 'Boxen', hinweis: 'Eine Sportart' },
  { id: 'i086', wort: 'Basketball', hinweis: 'Eine Sportart mit Ball' },
  { id: 'i087', wort: 'Golf', hinweis: 'Eine Sportart' },
  { id: 'i088', wort: 'Reiten', hinweis: 'Etwas mit einem Tier' },
  { id: 'i089', wort: 'Angeln', hinweis: 'Eine Freizeitaktivität' },
  { id: 'i090', wort: 'Klettern', hinweis: 'Eine sportliche Aktivität' },
  { id: 'i091', wort: 'Schach', hinweis: 'Ein Brettspiel' },
  { id: 'i092', wort: 'Poker', hinweis: 'Ein Kartenspiel' },
  { id: 'i093', wort: 'Kreuzworträtsel', hinweis: 'Ein Rätsel zum Zeitvertreib' },
  { id: 'i094', wort: 'Gitarre', hinweis: 'Ein Musikinstrument' },
  { id: 'i095', wort: 'Klavier', hinweis: 'Ein Musikinstrument' },
  { id: 'i096', wort: 'Trompete', hinweis: 'Ein Musikinstrument' },
  { id: 'i097', wort: 'Geige', hinweis: 'Ein Musikinstrument' },
  { id: 'i098', wort: 'Schlagzeug', hinweis: 'Ein Musikinstrument' },
  { id: 'i099', wort: 'Sushi', hinweis: 'Etwas zu essen' },
  { id: 'i100', wort: 'Currywurst', hinweis: 'Etwas zu essen' },
  { id: 'i101', wort: 'Döner', hinweis: 'Etwas zu essen' },
  { id: 'i102', wort: 'Hamburger', hinweis: 'Etwas zu essen' },
  { id: 'i103', wort: 'Pommes', hinweis: 'Etwas zu essen' },
  { id: 'i104', wort: 'Schokolade', hinweis: 'Etwas Süßes' },
  { id: 'i105', wort: 'Eis', hinweis: 'Etwas Kaltes zum Essen' },
  { id: 'i106', wort: 'Kekse', hinweis: 'Etwas Süßes zum Essen' },
  { id: 'i107', wort: 'Limonade', hinweis: 'Ein süßes Getränk' },
  { id: 'i108', wort: 'Smoothie', hinweis: 'Ein Getränk aus Obst' },
  { id: 'i109', wort: 'Cappuccino', hinweis: 'Ein Getränk mit Kaffee' },
  { id: 'i110', wort: 'Rotwein', hinweis: 'Ein alkoholisches Getränk' },
  { id: 'i111', wort: 'Sekt', hinweis: 'Ein alkoholisches Getränk' },
  { id: 'i112', wort: 'Cocktail', hinweis: 'Ein gemischtes Getränk' },
  { id: 'i113', wort: 'Krankenhaus', hinweis: 'Ein Ort für Kranke' },
  { id: 'i114', wort: 'Apotheke', hinweis: 'Ein Ort für Medikamente' },
  { id: 'i115', wort: 'Friedhof', hinweis: 'Ein Ort der Ruhe' },
  { id: 'i116', wort: 'Moschee', hinweis: 'Ein Ort zum Beten' },
  { id: 'i117', wort: 'Tankstelle', hinweis: 'Ein Ort fürs Auto' },
  { id: 'i118', wort: 'Werkstatt', hinweis: 'Ein Ort fürs Auto' },
  { id: 'i119', wort: 'Baumarkt', hinweis: 'Ein Ort zum Einkaufen' },
  { id: 'i120', wort: 'Elefant', hinweis: 'Ein großes Tier' },
];
