/**
 * Paare für "Entweder-oder".
 *
 * Alle Mitspieler tippen gleichzeitig A oder B, die Minderheit trinkt. Jedes
 * Paar muss echt spalten: Beide Seiten sind eine ernsthafte Wahl, keine
 * Scheinalternative. Neue Paare hängen hinten an, Kennungen ändern sich nie.
 */

import type { EntwederOder } from './typen.js';

export const ENTWEDER_ODER: readonly EntwederOder[] = [
  { id: 'e001', a: 'Meer', b: 'Berge' },
  { id: 'e002', a: 'Kaffee', b: 'Tee' },
  { id: 'e003', a: 'Frühaufsteher', b: 'Nachtmensch' },
  { id: 'e004', a: 'Pizza', b: 'Burger' },
  { id: 'e005', a: 'Sommer', b: 'Winter' },
  { id: 'e006', a: 'Hund', b: 'Katze' },
  { id: 'e007', a: 'Netflix', b: 'Kino' },
  { id: 'e008', a: 'Strandurlaub', b: 'Städtetrip' },
  { id: 'e009', a: 'Ketchup', b: 'Mayo' },
  { id: 'e010', a: 'Morgens duschen', b: 'Abends duschen' },
  { id: 'e011', a: 'Süß', b: 'Salzig' },
  { id: 'e012', a: 'Buch', b: 'Hörbuch' },
  { id: 'e013', a: 'Camping', b: 'Hotel' },
  { id: 'e014', a: 'Auto', b: 'Fahrrad' },
  { id: 'e015', a: 'Stadtleben', b: 'Landleben' },
  { id: 'e016', a: 'Sonnenaufgang', b: 'Sonnenuntergang' },
  { id: 'e017', a: 'Cola', b: 'Fanta' },
  { id: 'e018', a: 'Chips', b: 'Popcorn' },
  { id: 'e019', a: 'Wandern', b: 'Schwimmen' },
  { id: 'e020', a: 'Wein', b: 'Bier' },
  { id: 'e021', a: 'Handschrift', b: 'Tippen' },
  { id: 'e022', a: 'Serie', b: 'Film' },
  { id: 'e023', a: 'Musik laut', b: 'Musik leise' },
  { id: 'e024', a: 'Süßes Frühstück', b: 'Herzhaftes Frühstück' },
  { id: 'e025', a: 'Fußball', b: 'Basketball' },
  { id: 'e026', a: 'Schnee', b: 'Sonnenschein' },
  { id: 'e027', a: 'Zugfahrt', b: 'Flugreise' },
  { id: 'e028', a: 'Katze', b: 'Hamster' },
  { id: 'e029', a: 'Pasta', b: 'Reis' },
  { id: 'e030', a: 'Grillen', b: 'Backen' },
  { id: 'e031', a: 'Zelten', b: 'Ferienwohnung' },
  { id: 'e032', a: 'Puzzle', b: 'Brettspiel' },
  { id: 'e033', a: 'Kartenspiel', b: 'Würfelspiel' },
  { id: 'e034', a: 'SMS', b: 'Telefonanruf' },
  { id: 'e035', a: 'Frühling', b: 'Herbst' },
  { id: 'e036', a: 'Wald', b: 'Strand' },
  { id: 'e037', a: 'Tee süß', b: 'Tee pur' },
  { id: 'e038', a: 'Comic', b: 'Roman' },
  { id: 'e039', a: 'Podcast', b: 'Playlist' },
  { id: 'e040', a: 'Fensterplatz', b: 'Gangplatz' },
  { id: 'e041', a: 'Frühstück', b: 'Kein Frühstück' },
  { id: 'e042', a: 'Ordnung', b: 'Kreatives Chaos' },
  { id: 'e043', a: 'Plan', b: 'Spontan' },
  { id: 'e044', a: 'Frühe Party', b: 'Späte Party' },
  { id: 'e045', a: 'Karaoke', b: 'Tanzen' },
  { id: 'e046', a: 'Museum', b: 'Freizeitpark' },
  { id: 'e047', a: 'Insel', b: 'Metropole' },
  { id: 'e048', a: 'Zoo', b: 'Aquarium' },
  { id: 'e049', a: 'Sushi', b: 'Döner' },
  { id: 'e050', a: 'Nudeln', b: 'Kartoffeln' },
  { id: 'e051', a: 'Apfel', b: 'Banane' },
  { id: 'e052', a: 'Erdbeere', b: 'Himbeere' },
  { id: 'e053', a: 'Eis', b: 'Kuchen' },
  { id: 'e054', a: 'Kekse', b: 'Salzstangen' },
  { id: 'e055', a: 'Limo', b: 'Wasser' },
  { id: 'e056', a: 'Currywurst', b: 'Schnitzel' },
  { id: 'e057', a: 'Vanilleeis', b: 'Schokoeis' },
  { id: 'e058', a: 'Scharf', b: 'Mild' },
  { id: 'e059', a: 'Popcorn süß', b: 'Popcorn salzig' },
  { id: 'e060', a: 'Rucksack', b: 'Koffer' },
  { id: 'e061', a: 'Zelt', b: 'Wohnmobil' },
  { id: 'e062', a: 'Norden', b: 'Süden' },
  { id: 'e063', a: 'Frühbucher', b: 'Last-Minute' },
  { id: 'e064', a: 'Inlandsurlaub', b: 'Auslandsreise' },
  { id: 'e065', a: 'Konzert', b: 'Festival' },
  { id: 'e066', a: 'Fantasy', b: 'Krimi' },
  { id: 'e067', a: 'Actionfilm', b: 'Komödie' },
  { id: 'e068', a: 'Serienmarathon', b: 'Kinoabend' },
  { id: 'e069', a: 'Wecker', b: 'Ausschlafen' },
  { id: 'e070', a: 'Frühstück im Bett', b: 'Frühstück am Tisch' },
  { id: 'e071', a: 'Fenster auf', b: 'Fenster zu' },
  { id: 'e072', a: 'Dusche', b: 'Vollbad' },
  { id: 'e073', a: 'Heiß duschen', b: 'Kalt duschen' },
  { id: 'e074', a: 'Joggen', b: 'Radfahren' },
  { id: 'e075', a: 'Yoga', b: 'Fitnessstudio' },
  { id: 'e076', a: 'Skifahren', b: 'Snowboarden' },
  { id: 'e077', a: 'Frühsport', b: 'Abendsport' },
  { id: 'e078', a: 'Team-Sport', b: 'Einzel-Sport' },
  { id: 'e079', a: 'Regen', b: 'Wind' },
  { id: 'e080', a: 'Klimaanlage', b: 'Ventilator' },
  { id: 'e081', a: 'Winterjacke', b: 'Regenjacke' },
  { id: 'e082', a: 'Aufräumen', b: 'Chaos lassen' },
  { id: 'e083', a: 'WhatsApp', b: 'E-Mail' },
  { id: 'e084', a: 'iOS', b: 'Android' },
  { id: 'e085', a: 'Kopfhörer', b: 'Lautsprecher' },
  { id: 'e086', a: 'Kopfhörer kabellos', b: 'Kopfhörer mit Kabel' },
  { id: 'e087', a: 'Handy', b: 'Laptop' },
  { id: 'e088', a: 'Zeitung', b: 'Nachrichten-App' },
  { id: 'e089', a: 'Fotos machen', b: 'Im Moment sein' },
  { id: 'e090', a: 'Selfie', b: 'Landschaftsfoto' },
  { id: 'e091', a: 'Sprachnachricht', b: 'Textnachricht' },
  { id: 'e092', a: 'Bahn', b: 'Auto' },
  { id: 'e093', a: 'Frühschicht', b: 'Spätschicht' },
  { id: 'e094', a: 'Homeoffice', b: 'Büro' },
  { id: 'e095', a: 'Wanderschuhe', b: 'Sneaker' },
  { id: 'e096', a: 'Regenschirm', b: 'Kapuze' },
  { id: 'e097', a: 'Mütze', b: 'Cap' },
  { id: 'e098', a: 'Tageslicht', b: 'Kunstlicht' },
  { id: 'e099', a: 'Erste Reihe', b: 'Hintere Reihe' },
  { id: 'e100', a: 'Serie auf Deutsch', b: 'Serie auf Englisch' },
];
