/**
 * Wortpaare fuer Imposter.
 *
 * Alle Mitspieler bekommen `wort`, der Imposter das aehnliche `falsch`.
 * Neue Paare werden HINTEN angehaengt, mit der naechsten freien Kennung
 * (`i121`, `i122`, ...). Bestehende Kennungen werden nie umbenannt oder
 * neu vergeben, da sie in abgelegten Rundenprotokollen stehen.
 */

import type { ImposterWort } from './typen.js';

export const IMPOSTER_WOERTER: readonly ImposterWort[] = [
  { id: 'i001', wort: 'Strand', falsch: 'Wüste' },
  { id: 'i002', wort: 'Zahnarzt', falsch: 'Friseur' },
  { id: 'i003', wort: 'Fahrrad', falsch: 'Motorrad' },
  { id: 'i004', wort: 'Hochzeit', falsch: 'Beerdigung' },
  { id: 'i005', wort: 'Schwimmbad', falsch: 'Sauna' },
  { id: 'i006', wort: 'Pizza', falsch: 'Lasagne' },
  { id: 'i007', wort: 'Hund', falsch: 'Wolf' },
  { id: 'i008', wort: 'Katze', falsch: 'Fuchs' },
  { id: 'i009', wort: 'Kaffee', falsch: 'Tee' },
  { id: 'i010', wort: 'Bahnhof', falsch: 'Flughafen' },
  { id: 'i011', wort: 'Schule', falsch: 'Universität' },
  { id: 'i012', wort: 'Lehrer', falsch: 'Trainer' },
  { id: 'i013', wort: 'Arzt', falsch: 'Krankenpfleger' },
  { id: 'i014', wort: 'Polizist', falsch: 'Wachmann' },
  { id: 'i015', wort: 'Supermarkt', falsch: 'Kiosk' },
  { id: 'i016', wort: 'Restaurant', falsch: 'Imbiss' },
  { id: 'i017', wort: 'Kino', falsch: 'Theater' },
  { id: 'i018', wort: 'Fußball', falsch: 'Handball' },
  { id: 'i019', wort: 'Tennis', falsch: 'Badminton' },
  { id: 'i020', wort: 'Skifahren', falsch: 'Snowboarden' },
  { id: 'i021', wort: 'Kuchen', falsch: 'Torte' },
  { id: 'i022', wort: 'Brot', falsch: 'Brötchen' },
  { id: 'i023', wort: 'Apfel', falsch: 'Birne' },
  { id: 'i024', wort: 'Zitrone', falsch: 'Limette' },
  { id: 'i025', wort: 'Bier', falsch: 'Wein' },
  { id: 'i026', wort: 'Whisky', falsch: 'Rum' },
  { id: 'i027', wort: 'Zug', falsch: 'Straßenbahn' },
  { id: 'i028', wort: 'Bus', falsch: 'Reisebus' },
  { id: 'i029', wort: 'Boot', falsch: 'Kanu' },
  { id: 'i030', wort: 'Flugzeug', falsch: 'Hubschrauber' },
  { id: 'i031', wort: 'Berg', falsch: 'Hügel' },
  { id: 'i032', wort: 'Fluss', falsch: 'Bach' },
  { id: 'i033', wort: 'See', falsch: 'Teich' },
  { id: 'i034', wort: 'Wald', falsch: 'Park' },
  { id: 'i035', wort: 'Wiese', falsch: 'Feld' },
  { id: 'i036', wort: 'Regenschirm', falsch: 'Sonnenschirm' },
  { id: 'i037', wort: 'Jacke', falsch: 'Mantel' },
  { id: 'i038', wort: 'Hose', falsch: 'Rock' },
  { id: 'i039', wort: 'Schuhe', falsch: 'Sandalen' },
  { id: 'i040', wort: 'Mütze', falsch: 'Hut' },
  { id: 'i041', wort: 'Handschuhe', falsch: 'Fäustlinge' },
  { id: 'i042', wort: 'Sofa', falsch: 'Sessel' },
  { id: 'i043', wort: 'Bett', falsch: 'Couch' },
  { id: 'i044', wort: 'Tisch', falsch: 'Schreibtisch' },
  { id: 'i045', wort: 'Stuhl', falsch: 'Hocker' },
  { id: 'i046', wort: 'Fenster', falsch: 'Balkontür' },
  { id: 'i047', wort: 'Garten', falsch: 'Balkon' },
  { id: 'i048', wort: 'Keller', falsch: 'Dachboden' },
  { id: 'i049', wort: 'Küche', falsch: 'Speisekammer' },
  { id: 'i050', wort: 'Bäcker', falsch: 'Konditor' },
  { id: 'i051', wort: 'Metzger', falsch: 'Fischhändler' },
  { id: 'i052', wort: 'Koch', falsch: 'Kellner' },
  { id: 'i053', wort: 'Pilot', falsch: 'Fluglotse' },
  { id: 'i054', wort: 'Kapitän', falsch: 'Matrose' },
  { id: 'i055', wort: 'Feuerwehrmann', falsch: 'Sanitäter' },
  { id: 'i056', wort: 'Anwalt', falsch: 'Richter' },
  { id: 'i057', wort: 'Priester', falsch: 'Mönch' },
  { id: 'i058', wort: 'König', falsch: 'Prinz' },
  { id: 'i059', wort: 'Ritter', falsch: 'Soldat' },
  { id: 'i060', wort: 'Pirat', falsch: 'Cowboy' },
  { id: 'i061', wort: 'Detektiv', falsch: 'Spion' },
  { id: 'i062', wort: 'Clown', falsch: 'Zauberer' },
  { id: 'i063', wort: 'Tänzer', falsch: 'Sänger' },
  { id: 'i064', wort: 'Schauspieler', falsch: 'Regisseur' },
  { id: 'i065', wort: 'Fotograf', falsch: 'Maler' },
  { id: 'i066', wort: 'Schneider', falsch: 'Weber' },
  { id: 'i067', wort: 'Bauer', falsch: 'Gärtner' },
  { id: 'i068', wort: 'Jäger', falsch: 'Angler' },
  { id: 'i069', wort: 'Camping', falsch: 'Wandern' },
  { id: 'i070', wort: 'Kreuzfahrt', falsch: 'Städtereise' },
  { id: 'i071', wort: 'Skiurlaub', falsch: 'Wellnessurlaub' },
  { id: 'i072', wort: 'Grillfest', falsch: 'Gartenparty' },
  { id: 'i073', wort: 'Geburtstag', falsch: 'Jubiläum' },
  { id: 'i074', wort: 'Weihnachten', falsch: 'Silvester' },
  { id: 'i075', wort: 'Ostern', falsch: 'Erntedankfest' },
  { id: 'i076', wort: 'Karneval', falsch: 'Oktoberfest' },
  { id: 'i077', wort: 'Konzert', falsch: 'Festival' },
  { id: 'i078', wort: 'Zirkus', falsch: 'Jahrmarkt' },
  { id: 'i079', wort: 'Museum', falsch: 'Bibliothek' },
  { id: 'i080', wort: 'Aquarium', falsch: 'Zoo' },
  { id: 'i081', wort: 'Achterbahn', falsch: 'Karussell' },
  { id: 'i082', wort: 'Schwimmen', falsch: 'Tauchen' },
  { id: 'i083', wort: 'Joggen', falsch: 'Walken' },
  { id: 'i084', wort: 'Yoga', falsch: 'Pilates' },
  { id: 'i085', wort: 'Boxen', falsch: 'Ringen' },
  { id: 'i086', wort: 'Basketball', falsch: 'Volleyball' },
  { id: 'i087', wort: 'Golf', falsch: 'Minigolf' },
  { id: 'i088', wort: 'Reiten', falsch: 'Voltigieren' },
  { id: 'i089', wort: 'Angeln', falsch: 'Segeln' },
  { id: 'i090', wort: 'Klettern', falsch: 'Bouldern' },
  { id: 'i091', wort: 'Schach', falsch: 'Dame' },
  { id: 'i092', wort: 'Poker', falsch: 'Skat' },
  { id: 'i093', wort: 'Kreuzworträtsel', falsch: 'Sudoku' },
  { id: 'i094', wort: 'Gitarre', falsch: 'Ukulele' },
  { id: 'i095', wort: 'Klavier', falsch: 'Keyboard' },
  { id: 'i096', wort: 'Trompete', falsch: 'Posaune' },
  { id: 'i097', wort: 'Geige', falsch: 'Bratsche' },
  { id: 'i098', wort: 'Schlagzeug', falsch: 'Cajon' },
  { id: 'i099', wort: 'Sushi', falsch: 'Sashimi' },
  { id: 'i100', wort: 'Currywurst', falsch: 'Bratwurst' },
  { id: 'i101', wort: 'Döner', falsch: 'Gyros' },
  { id: 'i102', wort: 'Hamburger', falsch: 'Hotdog' },
  { id: 'i103', wort: 'Pommes', falsch: 'Kartoffelchips' },
  { id: 'i104', wort: 'Schokolade', falsch: 'Marzipan' },
  { id: 'i105', wort: 'Eis', falsch: 'Sorbet' },
  { id: 'i106', wort: 'Kekse', falsch: 'Muffins' },
  { id: 'i107', wort: 'Limonade', falsch: 'Saft' },
  { id: 'i108', wort: 'Smoothie', falsch: 'Milchshake' },
  { id: 'i109', wort: 'Cappuccino', falsch: 'Milchkaffee' },
  { id: 'i110', wort: 'Rotwein', falsch: 'Weißwein' },
  { id: 'i111', wort: 'Sekt', falsch: 'Champagner' },
  { id: 'i112', wort: 'Cocktail', falsch: 'Bowle' },
  { id: 'i113', wort: 'Krankenhaus', falsch: 'Arztpraxis' },
  { id: 'i114', wort: 'Apotheke', falsch: 'Drogerie' },
  { id: 'i115', wort: 'Friedhof', falsch: 'Kapelle' },
  { id: 'i116', wort: 'Moschee', falsch: 'Synagoge' },
  { id: 'i117', wort: 'Tankstelle', falsch: 'Autowaschanlage' },
  { id: 'i118', wort: 'Werkstatt', falsch: 'Autohaus' },
  { id: 'i119', wort: 'Baumarkt', falsch: 'Gartencenter' },
  { id: 'i120', wort: 'Elefant', falsch: 'Nashorn' },
];
