/**
 * Sprueche fuer "Ich hab noch nie".
 *
 * Jede Runde deckt eine Aussage auf; wer sie doch schon erlebt hat, trinkt.
 * Die Auswahl zielt auf Alltagspannen, die in einer gemischten Runde von 4
 * bis 12 Leuten meistens jemanden treffen, aber nie alle gleichzeitig.
 *
 * Neue Eintraege werden hinten angehaengt, mit der naechsten freien
 * Kennung. Bestehende Kennungen aendern sich nie, auch nicht beim Umsortieren.
 */
import type { Spruch } from './typen.js';

export const NIEMALS_SPRUECHE: readonly Spruch[] = [
  { id: 'n001', text: 'Ich hab noch nie ein Auto rückwärts gegen einen Poller gesetzt.' },
  { id: 'n002', text: 'Ich hab mich noch nie ausgesperrt, weil der Schlüssel drinnen lag.' },
  { id: 'n003', text: 'Ich hab noch nie eine Zimmerpflanze totgepflegt, obwohl sie als pflegeleicht galt.' },
  { id: 'n004', text: 'Ich hab noch nie die Wäsche tagelang in der Maschine vergessen, bis sie roch.' },
  { id: 'n005', text: 'Ich hab noch nie den Herd angelassen und erst an der Bushaltestelle daran gedacht.' },
  { id: 'n006', text: 'Ich hab noch nie eine Notiz geschrieben und später selbst nicht mehr entziffern können.' },
  { id: 'n007', text: 'Ich hab noch nie den Wecker gehört, ausgemacht und danach nochmal verschlafen.' },
  { id: 'n008', text: 'Ich hab noch nie bei einem Ikea-Möbel eine Schraube übrig gehabt und trotzdem weitergemacht.' },
  { id: 'n009', text: 'Ich hab noch nie den Müll runtergebracht und danach vor der zugefallenen Wohnungstür gestanden.' },
  { id: 'n010', text: 'Ich hab noch nie Nudeln aufgesetzt und komplett vergessen, bis der Topf überkochte.' },
  { id: 'n011', text: 'Ich hab noch nie die Fernbedienung im Kühlschrank wiedergefunden.' },
  { id: 'n012', text: 'Ich hab noch nie in einer Videokonferenz laut mitgesungen, ohne das Mikro stumm zu schalten.' },
  { id: 'n013', text: 'Ich hab noch nie eine E-Mail an den falschen Verteiler geschickt.' },
  { id: 'n014', text: 'Ich hab mich noch nie in einer Präsentation verhaspelt und komplett neu angefangen.' },
  { id: 'n015', text: 'Ich hab noch nie eine Hausaufgabe erst auf dem Weg zur Schule gemacht.' },
  { id: 'n016', text: 'Ich hab noch nie im Bewerbungsgespräch den Namen der Firma falsch ausgesprochen.' },
  { id: 'n017', text: 'Ich hab noch nie eine Deadline um Minuten verpasst, weil der Upload ewig dauerte.' },
  { id: 'n018', text: 'Ich hab mich noch nie in der Kaffeeküche über einen Kollegen ausgelassen, der direkt hinter mir stand.' },
  { id: 'n019', text: 'Ich hab noch nie in einer Besprechung eingenickt und rechtzeitig wieder aufgewacht.' },
  { id: 'n020', text: 'Ich hab noch nie eine wichtige Datei kurz vor der Abgabe versehentlich überschrieben.' },
  { id: 'n021', text: 'Ich hab noch nie eine Kundin mit dem falschen Namen angesprochen.' },
  { id: 'n022', text: 'Ich hab noch nie am Flughafen das falsche Gate angesteuert, bis die Anzeige zweimal blinkte.' },
  { id: 'n023', text: 'Ich hab noch nie im Ausland mit Händen und Füßen nach der nächsten Toilette gefragt.' },
  { id: 'n024', text: 'Ich hab noch nie den Koffer erst am Tag der Abreise gepackt, weil vorher keine Zeit war.' },
  { id: 'n025', text: 'Ich hab noch nie im Zug in die falsche Richtung gefahren und das erst nach zwei Stationen gemerkt.' },
  { id: 'n026', text: 'Ich hab noch nie ein Souvenir gekauft, das ich seither nie wieder ausgepackt habe.' },
  { id: 'n027', text: 'Ich hab noch nie den Reisepass kurz vor der Abfahrt fast zu Hause liegen lassen.' },
  { id: 'n028', text: 'Ich hab noch nie im Hotel die Zimmernummer vergessen und an der falschen Tür geklopft.' },
  { id: 'n029', text: 'Ich hab mich noch nie am Urlaubsort komplett verlaufen und mit der Karte im Kreis gedreht.' },
  { id: 'n030', text: 'Ich hab noch nie eine Fähre nur um Sekunden erreicht, weil ich gerannt bin wie verrückt.' },
  { id: 'n031', text: 'Ich hab noch nie im Flugzeug den Sitzplatz des Nachbarn mit meinem verwechselt.' },
  { id: 'n032', text: 'Ich hab noch nie das Handy im Klo fallen lassen und danach panisch trockengelegt.' },
  { id: 'n033', text: 'Ich hab noch nie eine Sprachnachricht doppelt so lang aufgenommen, wie eigentlich geplant war.' },
  { id: 'n034', text: 'Ich hab noch nie das Passwort so oft falsch eingegeben, dass der Account gesperrt wurde.' },
  { id: 'n035', text: 'Ich hab noch nie beim Bildschirmteilen aus Versehen private Fotos gezeigt.' },
  { id: 'n036', text: 'Ich hab noch nie beim Beamen einen Tab offen gehabt, den ich lieber niemandem gezeigt hätte.' },
  { id: 'n037', text: 'Ich hab noch nie eine Autokorrektur zu spät gesehen und peinlichen Unsinn abgeschickt.' },
  { id: 'n038', text: 'Ich hab noch nie das Handy im Flugmodus vergessen und stundenlang keine Nachricht bekommen.' },
  { id: 'n039', text: 'Ich hab noch nie während einer Besprechung einen privaten Anruf angenommen.' },
  { id: 'n040', text: 'Ich hab noch nie eine App zwanzig Minuten neu gestartet, weil sie angeblich nicht funktionierte.' },
  { id: 'n041', text: 'Ich hab noch nie mein eigenes WLAN-Passwort vergessen, obwohl es an der Fritzbox klebte.' },
  { id: 'n042', text: 'Ich hab noch nie ein Gericht bestellt, dessen Namen ich nicht aussprechen konnte.' },
  { id: 'n043', text: 'Ich hab noch nie beim Kochen die ganze Küche eingenebelt, weil etwas angebrannt ist.' },
  { id: 'n044', text: 'Ich hab noch nie einen Kuchen ohne Zucker gebacken, weil ich die Zutat vergessen habe.' },
  { id: 'n045', text: 'Ich hab noch nie in einem Restaurant das Trinkgeld aus Versehen doppelt bezahlt.' },
  { id: 'n046', text: 'Ich hab noch nie eine Chilischote unterschätzt und danach nur noch Milch getrunken.' },
  { id: 'n047', text: 'Ich hab mir noch nie beim Grillen fast die Augenbrauen versengt.' },
  { id: 'n048', text: 'Ich hab mir noch nie am Buffet mehr aufgeladen, als ich am Ende essen konnte.' },
  { id: 'n049', text: 'Ich hab noch nie ein Gericht nachbestellt, das ich beim ersten Mal kaum angerührt hatte.' },
  { id: 'n050', text: 'Ich hab noch nie Eiswürfel für Brühwürfel gehalten und versehentlich in den Tee geworfen.' },
  { id: 'n051', text: 'Ich hab noch nie eine Torte gebacken, die beim Anschneiden komplett in sich zusammenfiel.' },
  { id: 'n052', text: 'Ich hab noch nie beim Einparken den Bordstein als Ersatzbremse benutzt.' },
  { id: 'n053', text: 'Ich hab noch nie den Blinker über eine ganze Autobahnfahrt anlassen.' },
  { id: 'n054', text: 'Ich hab mich noch nie im Parkhaus so verfahren, dass ich zweimal an derselben Ausfahrt vorbeikam.' },
  { id: 'n055', text: 'Ich hab noch nie an einer roten Ampel losgefahren, weil das Auto davor schon angefahren ist.' },
  { id: 'n056', text: 'Ich hab noch nie das Fahrrad irgendwo abgestellt und danach zehn Minuten lang gesucht.' },
  { id: 'n057', text: 'Ich hab noch nie eine Verkehrsinsel im Halbdunkel für eine normale Spur gehalten.' },
  { id: 'n058', text: 'Ich hab noch nie im Bus die eigene Haltestelle verschlafen und eine Extrarunde mitgefahren.' },
  { id: 'n059', text: 'Ich hab noch nie beim Rückwärtseinparken den Bordstein touchiert.' },
  { id: 'n060', text: 'Ich hab mich noch nie beim Tanken an die falsche Seite der Zapfsäule gestellt.' },
  { id: 'n061', text: 'Ich hab noch nie den Blinker gesetzt und dann doch geradeaus weitergefahren.' },
  { id: 'n062', text: 'Ich hab noch nie bei einem Familienfest den Namen eines Cousins vergessen und nur „hey du" gesagt.' },
  { id: 'n063', text: 'Ich hab noch nie Weihnachtsgeschenke so knapp besorgt, dass ich sie noch im Auto eingepackt habe.' },
  { id: 'n064', text: 'Ich hab noch nie bei einer Familienfeier das falsche Geburtsjahr der Oma genannt.' },
  { id: 'n065', text: 'Ich hab noch nie eine Familien-Chatgruppe aus Versehen verlassen und um Wiederaufnahme gebeten.' },
  { id: 'n066', text: 'Ich hab noch nie beim Familienessen laut über jemanden geredet, der gerade zur Tür kam.' },
  { id: 'n067', text: 'Ich hab noch nie ein Geschenk bekommen, das ich selbst schon einmal verschenkt hatte.' },
  { id: 'n068', text: 'Ich hab noch nie bei einem Familientreffen das falsche Familienmitglied umarmt.' },
  { id: 'n069', text: 'Ich hab noch nie den Geburtstag eines Verwandten vergessen und erst am Tag danach gratuliert.' },
  { id: 'n070', text: 'Ich hab noch nie Tante und Cousine am Telefon verwechselt und munter weitergeplaudert.' },
  { id: 'n071', text: 'Ich hab noch nie bei einem Familienfoto als einzige oder einziger die Augen geschlossen gehabt.' },
  { id: 'n072', text: 'Ich hab noch nie beim Joggen die eigene Zeit schöner erzählt, als sie wirklich war.' },
  { id: 'n073', text: 'Ich hab noch nie im Fitnessstudio ein Gerät falsch eingestellt und mich damit blamiert.' },
  { id: 'n074', text: 'Ich hab noch nie bei einem Fußballspiel ins eigene Tor geschossen.' },
  { id: 'n075', text: 'Ich hab mich noch nie beim Aufwärmen stärker verletzt als beim eigentlichen Sport danach.' },
  { id: 'n076', text: 'Ich hab noch nie eine Wette unter Freunden verloren und die Aufgabe möglichst lange verschoben.' },
  { id: 'n077', text: 'Ich hab noch nie beim Schwimmen versehentlich in die Bahnabtrennung geschwommen.' },
  { id: 'n078', text: 'Ich hab noch nie beim Skifahren den Lift falsch bestiegen und gleich wieder absteigen müssen.' },
  { id: 'n079', text: 'Ich hab noch nie bei einem Wettkampf die Startnummer seitenverkehrt angesteckt.' },
  { id: 'n080', text: 'Ich hab noch nie eine Laufrunde heimlich abgekürzt und trotzdem von der guten Zeit erzählt.' },
  { id: 'n081', text: 'Ich hab noch nie beim Mannschaftssport den eigenen Namen falsch auf das Trikot drucken lassen.' },
  { id: 'n082', text: 'Ich hab noch nie auf einer Party den Gastgeber mit jemand anderem verwechselt.' },
  { id: 'n083', text: 'Ich hab noch nie bei einem Umtrunk aus dem falschen Glas weitergetrunken.' },
  { id: 'n084', text: 'Ich hab noch nie eine Karaoke-Nummer angemeldet und danach den Text komplett vergessen.' },
  { id: 'n085', text: 'Ich hab noch nie auf einer Feier denselben Witz zweimal derselben Person erzählt.' },
  { id: 'n086', text: 'Ich hab noch nie eine Einladung übersehen und das erst auf den Fotos danach gemerkt.' },
  { id: 'n087', text: 'Ich hab noch nie bei einem Spieleabend so lange geschummelt, bis es endlich aufgefallen ist.' },
  { id: 'n088', text: 'Ich hab noch nie mit dem völlig falschen Kostüm auf einer Mottoparty aufgetaucht.' },
  { id: 'n089', text: 'Ich hab noch nie auf einer Feier versehentlich das Namensschild einer fremden Person getragen.' },
  { id: 'n090', text: 'Ich hab noch nie beim Anstoßen ein fremdes Glas erwischt und trotzdem seelenruhig getrunken.' },
  { id: 'n091', text: 'Ich hab noch nie eine Party verlassen, ohne mich zu verabschieden, weil ich einfach zu müde war.' },
  { id: 'n092', text: 'Ich hab noch nie einen Kommentar unter dem völlig falschen Beitrag gepostet.' },
  { id: 'n093', text: 'Ich hab noch nie jemandem aus Versehen ein Like gegeben und es danach panisch wieder entfernt.' },
  { id: 'n094', text: 'Ich hab mich noch nie selbst gegoogelt und mehr gefunden, als mir eigentlich lieb war.' },
  { id: 'n095', text: 'Ich hab noch nie beim Online-Shopping die falsche Größe bestellt und sie trotzdem behalten.' },
  { id: 'n096', text: 'Ich hab noch nie ein altes Kindheitsfoto im Netz gefunden und sofort verschickt.' },
  { id: 'n097', text: 'Ich hab noch nie einen Kommentar geschrieben und ihn Minuten später heimlich wieder gelöscht.' },
  { id: 'n098', text: 'Ich hab noch nie jemandem aus Versehen ein „gefällt mir“ bei einem uralten Beitrag gegeben.' },
  { id: 'n099', text: 'Ich hab noch nie eine Story hochgeladen und danach entdeckt, wie unvorteilhaft das Foto war.' },
  { id: 'n100', text: 'Ich hab noch nie in einer Chat-Nachricht den falschen Namen angeschrieben und sie trotzdem abgeschickt.' },
  { id: 'n101', text: 'Ich hab noch nie gekifft und danach eine Stunde lang im Kühlschrank nach etwas gesucht.' },
  { id: 'n102', text: 'Ich hab noch nie bekifft einen Film angefangen und nach zehn Minuten vergessen, worum es ging.' },
  { id: 'n103', text: 'Ich hab noch nie behauptet, es rieche hier nach gar nichts.' },
  { id: 'n104', text: 'Ich hab noch nie bekifft versucht, eine ernste Nachricht zu tippen, und dreimal neu angefangen.' },
  { id: 'n105', text: 'Ich hab noch nie einen Joint gedreht, der aussah wie eine Karotte.' },
  { id: 'n106', text: 'Ich hab noch nie bekifft etwas gekocht, das hinterher niemand essen wollte.' },
  { id: 'n107', text: 'Ich hab noch nie bekifft gelacht, ohne dass irgendjemand wusste, worüber.' },
  { id: 'n108', text: 'Ich hab noch nie bekifft beschlossen, mein ganzes Leben umzukrempeln, und es am nächsten Tag vergessen.' },
  { id: 'n109', text: 'Ich hab noch nie so getan, als hätte ich noch nie gekifft.' },
  { id: 'n110', text: 'Ich hab noch nie bekifft am Kühlschrank gestanden und die Tür wieder zugemacht, ohne etwas herauszunehmen.' },
];
