/**
 * Katalog der Allgemeinwissensfragen fuer die Partykiste.
 *
 * Neue Fragen werden einfach hinten angehaengt, mit der naechsten freien
 * Kennung ('qNNN'). Bestehende Kennungen aendern sich nie, auch nicht bei
 * Korrekturen an Frage- oder Antworttext, weil sie in abgelegten
 * Rundenprotokollen stehen.
 */

import type { QuizFrage } from './typen.js';

export const QUIZ_FRAGEN: readonly QuizFrage[] = [
  { id: 'q001', frage: 'Welcher Planet ist der Sonne am nächsten?', antworten: ['Merkur', 'Venus', 'Mars', 'Erde'], richtig: 0 },
  { id: 'q002', frage: 'In welchem Jahr fiel die Berliner Mauer?', antworten: ['1987', '1989', '1991', '1993'], richtig: 1 },
  { id: 'q003', frage: 'Wie viele Beine hat eine Spinne?', antworten: ['6', '10', '8', '4'], richtig: 2 },
  { id: 'q004', frage: 'Wie viele Spieler stehen bei einer Fußballmannschaft auf dem Feld?', antworten: ['10', '9', '12', '11'], richtig: 3 },
  { id: 'q005', frage: 'Wie viele Saiten hat eine klassische Gitarre üblicherweise?', antworten: ['6', '4', '8', '12'], richtig: 0 },
  { id: 'q006', frage: 'Wer führte Regie bei \'Jurassic Park\'?', antworten: ['George Lucas', 'Steven Spielberg', 'James Cameron', 'Ridley Scott'], richtig: 1 },
  { id: 'q007', frage: 'Wer schrieb \'Romeo und Julia\'?', antworten: ['Charles Dickens', 'Oscar Wilde', 'William Shakespeare', 'Mark Twain'], richtig: 2 },
  { id: 'q008', frage: 'Aus welchem Land stammt die Pizza ursprünglich?', antworten: ['Griechenland', 'Spanien', 'Frankreich', 'Italien'], richtig: 3 },
  { id: 'q009', frage: 'Wie viele Fälle (Kasus) hat die deutsche Grammatik?', antworten: ['4', '3', '5', '6'], richtig: 0 },
  { id: 'q010', frage: 'Wer gilt als Erfinder der praxistauglichen Glühlampe?', antworten: ['Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'Benjamin Franklin'], richtig: 1 },
  { id: 'q011', frage: 'Welches ist das größte Landtier der Welt?', antworten: ['das Nashorn', 'die Giraffe', 'der Afrikanische Elefant', 'das Flusspferd'], richtig: 2 },
  { id: 'q012', frage: 'Wer malte die \'Mona Lisa\'?', antworten: ['Michelangelo', 'Raffael', 'Sandro Botticelli', 'Leonardo da Vinci'], richtig: 3 },
  { id: 'q013', frage: 'Wie heißt die Hauptstadt von Australien?', antworten: ['Canberra', 'Sydney', 'Melbourne', 'Perth'], richtig: 0 },
  { id: 'q014', frage: 'Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', antworten: ['Willy Brandt', 'Konrad Adenauer', 'Ludwig Erhard', 'Helmut Schmidt'], richtig: 1 },
  { id: 'q015', frage: 'Welches chemische Element hat das Symbol O?', antworten: ['Gold', 'Osmium', 'Sauerstoff', 'Wasserstoff'], richtig: 2 },
  { id: 'q016', frage: 'Bei welchem Turnier wird der Wimbledon-Pokal vergeben?', antworten: ['Golf', 'Squash', 'Badminton', 'Tennis'], richtig: 3 },
  { id: 'q017', frage: 'Welches Instrument hat schwarze und weiße Tasten?', antworten: ['das Klavier', 'die Geige', 'die Trompete', 'die Harfe'], richtig: 0 },
  { id: 'q018', frage: 'In welcher Stadt spielt die Serie \'Sex and the City\' hauptsächlich?', antworten: ['Los Angeles', 'New York', 'Chicago', 'Boston'], richtig: 1 },
  { id: 'q019', frage: 'Welcher Autor schrieb \'Der Prozess\' und \'Die Verwandlung\'?', antworten: ['Thomas Mann', 'Hermann Hesse', 'Franz Kafka', 'Bertolt Brecht'], richtig: 2 },
  { id: 'q020', frage: 'Womit wird Sushi-Reis traditionell gewürzt?', antworten: ['Sojasauce', 'Zitronensaft', 'Weinessig', 'Reisessig'], richtig: 3 },
  { id: 'q021', frage: 'Welche Sprache hat weltweit die meisten Muttersprachler?', antworten: ['Mandarin-Chinesisch', 'Englisch', 'Spanisch', 'Hindi'], richtig: 0 },
  { id: 'q022', frage: 'Wofür steht das \'www\' im Internet?', antworten: ['World Wide Wire', 'World Wide Web', 'Web Wide World', 'World Web Wire'], richtig: 1 },
  { id: 'q023', frage: 'Wie viele Herzen hat ein Krake?', antworten: ['1', '2', '3', '4'], richtig: 2 },
  { id: 'q024', frage: 'Welcher Maler schuf das Werk \'Sternennacht\'?', antworten: ['Paul Gauguin', 'Claude Monet', 'Edgar Degas', 'Vincent van Gogh'], richtig: 3 },
  { id: 'q025', frage: 'Welches Land hat die meisten Einwohner in Südamerika?', antworten: ['Brasilien', 'Argentinien', 'Kolumbien', 'Peru'], richtig: 0 },
  { id: 'q026', frage: 'In welchem Jahrhundert wurde Leonardo da Vinci geboren?', antworten: ['13. Jahrhundert', '15. Jahrhundert', '16. Jahrhundert', '17. Jahrhundert'], richtig: 1 },
  { id: 'q027', frage: 'Was ist die chemische Formel von Wasser?', antworten: ['CO2', 'NaCl', 'H2O', 'O2'], richtig: 2 },
  { id: 'q028', frage: 'Wie oft finden die Olympischen Sommerspiele planmäßig statt?', antworten: ['alle 2 Jahre', 'alle 3 Jahre', 'alle 5 Jahre', 'alle 4 Jahre'], richtig: 3 },
  { id: 'q029', frage: 'Wer komponierte die \'Mondscheinsonate\'?', antworten: ['Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'], richtig: 0 },
  { id: 'q030', frage: 'Welches Tier ist Simba im Film \'Der König der Löwen\'?', antworten: ['ein Tiger', 'ein Löwe', 'ein Leopard', 'ein Fuchs'], richtig: 1 },
  { id: 'q031', frage: 'In welchem Buch kommt die Figur Frodo Beutlin vor?', antworten: ['Harry Potter', 'Die Chroniken von Narnia', 'Der Herr der Ringe', 'Der Hobbit'], richtig: 2 },
  { id: 'q032', frage: 'Welches Getreide ist die klassische Grundlage für Bier?', antworten: ['Weizen', 'Reis', 'Mais', 'Gerste'], richtig: 3 },
  { id: 'q033', frage: 'Aus welcher Sprache stammt das englische Lehnwort \'Kindergarten\'?', antworten: ['Deutsch', 'Niederländisch', 'Schwedisch', 'Dänisch'], richtig: 0 },
  { id: 'q034', frage: 'Wer gründete das Unternehmen Microsoft mit?', antworten: ['Steve Jobs', 'Bill Gates', 'Larry Page', 'Mark Zuckerberg'], richtig: 1 },
  { id: 'q035', frage: 'Welches Tier gilt als schnellstes Landtier der Welt?', antworten: ['der Löwe', 'der Strauß', 'der Gepard', 'die Antilope'], richtig: 2 },
  { id: 'q036', frage: 'Welche Kunstrichtung wird mit Salvador Dalí verbunden?', antworten: ['Impressionismus', 'Kubismus', 'Barock', 'Surrealismus'], richtig: 3 },
  { id: 'q037', frage: 'Welcher Ozean ist der größte der Erde?', antworten: ['der Pazifik', 'der Atlantik', 'der Indische Ozean', 'der Arktische Ozean'], richtig: 0 },
  { id: 'q038', frage: 'In welchem Jahr begann der Erste Weltkrieg?', antworten: ['1912', '1914', '1916', '1918'], richtig: 1 },
  { id: 'q039', frage: 'Wie viele Knochen hat ein erwachsener Mensch normalerweise?', antworten: ['186', '226', '206', '300'], richtig: 2 },
  { id: 'q040', frage: 'Wie viele Ringe hat das olympische Symbol?', antworten: ['4', '6', '7', '5'], richtig: 3 },
  { id: 'q041', frage: 'Welche Band veröffentlichte das Album \'Abbey Road\'?', antworten: ['The Beatles', 'The Rolling Stones', 'Pink Floyd', 'Queen'], richtig: 0 },
  { id: 'q042', frage: 'Wer spielte Jack in \'Titanic\'?', antworten: ['Brad Pitt', 'Leonardo DiCaprio', 'Matt Damon', 'Tom Cruise'], richtig: 1 },
  { id: 'q043', frage: 'Wer schrieb \'Faust\'?', antworten: ['Friedrich Schiller', 'Heinrich Heine', 'Johann Wolfgang von Goethe', 'Theodor Fontane'], richtig: 2 },
  { id: 'q044', frage: 'Welche Frucht ist die Hauptzutat von Guacamole?', antworten: ['Tomate', 'Mango', 'Paprika', 'Avocado'], richtig: 3 },
  { id: 'q045', frage: 'Wie nennt man ein Wort, das vorwärts und rückwärts gelesen gleich lautet?', antworten: ['Palindrom', 'Anagramm', 'Akronym', 'Homonym'], richtig: 0 },
  { id: 'q046', frage: 'Was misst man in der Einheit Hertz?', antworten: ['Spannung', 'Frequenz', 'Stromstärke', 'Widerstand'], richtig: 1 },
  { id: 'q047', frage: 'Zu welcher Tiergruppe gehört der Delfin?', antworten: ['Fische', 'Amphibien', 'Säugetiere', 'Reptilien'], richtig: 2 },
  { id: 'q048', frage: 'Wer schuf die Deckenmalerei der Sixtinischen Kapelle?', antworten: ['Raffael', 'Leonardo da Vinci', 'Donatello', 'Michelangelo'], richtig: 3 },
  { id: 'q049', frage: 'Auf welchem Kontinent liegt die Sahara?', antworten: ['Afrika', 'Asien', 'Australien', 'Südamerika'], richtig: 0 },
  { id: 'q050', frage: 'Wer entdeckte 1492 den amerikanischen Kontinent aus europäischer Sicht?', antworten: ['Vasco da Gama', 'Christoph Kolumbus', 'Ferdinand Magellan', 'Amerigo Vespucci'], richtig: 1 },
  { id: 'q051', frage: 'Welches Organ pumpt das Blut durch den Körper?', antworten: ['die Leber', 'die Lunge', 'das Herz', 'die Niere'], richtig: 2 },
  { id: 'q052', frage: 'In welchem Land wurden die modernen Boxregeln (Queensberry) entwickelt?', antworten: ['die USA', 'Frankreich', 'Irland', 'England'], richtig: 3 },
  { id: 'q053', frage: 'Wie viele Tasten hat ein klassisches Klavier üblicherweise?', antworten: ['88', '76', '96', '61'], richtig: 0 },
  { id: 'q054', frage: 'Welcher Regisseur schuf die \'Star Wars\'-Filmreihe?', antworten: ['Steven Spielberg', 'George Lucas', 'James Cameron', 'Peter Jackson'], richtig: 1 },
  { id: 'q055', frage: 'Welches Märchen handelt von einem Mädchen mit rotem Umhang?', antworten: ['Schneewittchen', 'Aschenputtel', 'Rotkäppchen', 'Dornröschen'], richtig: 2 },
  { id: 'q056', frage: 'Aus welchem Land stammt der Käse Feta ursprünglich?', antworten: ['Italien', 'die Türkei', 'Bulgarien', 'Griechenland'], richtig: 3 },
  { id: 'q057', frage: 'Welches Alphabet verwendet die russische Sprache?', antworten: ['das kyrillische Alphabet', 'das lateinische Alphabet', 'das griechische Alphabet', 'das arabische Alphabet'], richtig: 0 },
  { id: 'q058', frage: 'Wie nennt man den kleinsten Baustein für Ja/Nein-Werte in der Computertechnik?', antworten: ['Byte', 'Bit', 'Pixel', 'Chip'], richtig: 1 },
  { id: 'q059', frage: 'Wie nennt man die Larve eines Schmetterlings?', antworten: ['Made', 'Puppe', 'Raupe', 'Nymphe'], richtig: 2 },
  { id: 'q060', frage: 'Welcher Künstler ist bekannt für seine Suppendosen-Kunstwerke?', antworten: ['Roy Lichtenstein', 'Jackson Pollock', 'Keith Haring', 'Andy Warhol'], richtig: 3 },
  { id: 'q061', frage: 'Welches Land grenzt nicht an Deutschland?', antworten: ['Italien', 'Polen', 'Österreich', 'die Niederlande'], richtig: 0 },
  { id: 'q062', frage: 'In welchem Jahr wurde Deutschland wiedervereinigt?', antworten: ['1989', '1990', '1991', '1988'], richtig: 1 },
  { id: 'q063', frage: 'Welches Gas geben Pflanzen bei der Fotosynthese ab?', antworten: ['Kohlendioxid', 'Stickstoff', 'Sauerstoff', 'Wasserstoff'], richtig: 2 },
  { id: 'q064', frage: 'Wie viele Punkte zählt ein Homerun beim Baseball mindestens?', antworten: ['2', '3', '4', '1'], richtig: 3 },
  { id: 'q065', frage: 'Welches Instrument wird mit einem Bogen gespielt?', antworten: ['die Violine', 'die Trompete', 'die Flöte', 'die Gitarre'], richtig: 0 },
  { id: 'q066', frage: 'In welchem Film sagt man \'Ich seh tote Menschen\'?', antworten: ['The Others', 'The Sixth Sense', 'Poltergeist', 'Ghost'], richtig: 1 },
  { id: 'q067', frage: 'Wer schrieb die Romanreihe \'Harry Potter\'?', antworten: ['Stephenie Meyer', 'Suzanne Collins', 'J.K. Rowling', 'Cassandra Clare'], richtig: 2 },
  { id: 'q068', frage: 'Welches Gewürz wird aus den Narben der Krokusblüte gewonnen?', antworten: ['Kurkuma', 'Paprika', 'Zimt', 'Safran'], richtig: 3 },
  { id: 'q069', frage: 'Wie viele Buchstaben hat das deutsche Alphabet inklusive Umlauten und ß?', antworten: ['30', '26', '28', '32'], richtig: 0 },
  { id: 'q070', frage: 'Welches Unternehmen entwickelte das Betriebssystem iOS?', antworten: ['Google', 'Apple', 'Microsoft', 'Samsung'], richtig: 1 },
  { id: 'q071', frage: 'Welches Tier trägt seine Jungen in einem Beutel?', antworten: ['der Panda', 'der Waschbär', 'das Känguru', 'das Stachelschwein'], richtig: 2 },
  { id: 'q072', frage: 'Welche Kunstrichtung von Picasso zeigt zersplitterte, geometrische Formen?', antworten: ['Impressionismus', 'Expressionismus', 'Barock', 'Kubismus'], richtig: 3 },
  { id: 'q073', frage: 'Wie heißt die Hauptstadt von Kanada?', antworten: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'], richtig: 0 },
  { id: 'q074', frage: 'Welcher Pharao ließ vermutlich die große Pyramide von Gizeh errichten?', antworten: ['Ramses II.', 'Cheops', 'Tutanchamun', 'Echnaton'], richtig: 1 },
  { id: 'q075', frage: 'Wie nennt man die Lehre von Sternen und Planeten?', antworten: ['Astrologie', 'Geologie', 'Astronomie', 'Meteorologie'], richtig: 2 },
  { id: 'q076', frage: 'Bei welcher Sportart schlägt man den Ball über ein Netz und darf ihn nicht fangen?', antworten: ['Basketball', 'Handball', 'Wasserball', 'Volleyball'], richtig: 3 },
  { id: 'q077', frage: 'Aus welchem Land stammt der Tango als Musik- und Tanzstil?', antworten: ['Argentinien', 'Spanien', 'Brasilien', 'Mexiko'], richtig: 0 },
  { id: 'q078', frage: 'Wer spielte Harry Potter in der gleichnamigen Filmreihe?', antworten: ['Rupert Grint', 'Daniel Radcliffe', 'Elijah Wood', 'Tom Felton'], richtig: 1 },
  { id: 'q079', frage: 'In welchem Jahrhundert wurde William Shakespeare geboren?', antworten: ['15. Jahrhundert', '17. Jahrhundert', '16. Jahrhundert', '18. Jahrhundert'], richtig: 2 },
  { id: 'q080', frage: 'Was ist die Hauptzutat von Hummus?', antworten: ['Linsen', 'weiße Bohnen', 'Erdnüsse', 'Kichererbsen'], richtig: 3 },
  { id: 'q081', frage: 'Was bedeutet das lateinische Wort \'aqua\'?', antworten: ['Wasser', 'Feuer', 'Erde', 'Luft'], richtig: 0 },
  { id: 'q082', frage: 'Wofür steht die Abkürzung \'PDF\'?', antworten: ['Personal Data File', 'Portable Document Format', 'Printable Document Format', 'Public Data Format'], richtig: 1 },
  { id: 'q083', frage: 'Wie viele Beine hat ein Insekt?', antworten: ['8', '4', '6', '10'], richtig: 2 },
  { id: 'q084', frage: 'In welchem Museum hängt die \'Mona Lisa\' im Original?', antworten: ['im Prado in Madrid', 'in der Tate Gallery', 'in den Uffizien', 'im Louvre in Paris'], richtig: 3 },
  { id: 'q085', frage: 'Welcher Berg ist der höchste der Welt?', antworten: ['der Mount Everest', 'der K2', 'der Kilimandscharo', 'der Mont Blanc'], richtig: 0 },
  { id: 'q086', frage: 'In welchem Jahr sank die Titanic?', antworten: ['1905', '1912', '1918', '1923'], richtig: 1 },
  { id: 'q087', frage: 'Welches ist das härteste natürlich vorkommende Material?', antworten: ['Titan', 'Quarz', 'Diamant', 'Granit'], richtig: 2 },
  { id: 'q088', frage: 'Wie lang ist ein Marathonlauf ungefähr?', antworten: ['30 km', '50 km', '21 km', '42 km'], richtig: 3 },
  { id: 'q089', frage: 'Wer schrieb die Oper \'Die Zauberflöte\'?', antworten: ['Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Richard Wagner', 'Giuseppe Verdi'], richtig: 0 },
  { id: 'q090', frage: 'In welchem Land wurde der Film \'Amélie\' produziert?', antworten: ['Italien', 'Frankreich', 'Spanien', 'Belgien'], richtig: 1 },
  { id: 'q091', frage: 'Wer schrieb \'1984\' und \'Farm der Tiere\'?', antworten: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'], richtig: 2 },
  { id: 'q092', frage: 'Welches Land ist das Ursprungsland des Champagners?', antworten: ['Italien', 'Spanien', 'Deutschland', 'Frankreich'], richtig: 3 },
  { id: 'q093', frage: 'In welchem südamerikanischen Land ist Portugiesisch Amtssprache?', antworten: ['Brasilien', 'Argentinien', 'Chile', 'Venezuela'], richtig: 0 },
  { id: 'q094', frage: 'Wer patentierte 1876 als Erster das Telefon?', antworten: ['Thomas Edison', 'Alexander Graham Bell', 'Guglielmo Marconi', 'Nikola Tesla'], richtig: 1 },
  { id: 'q095', frage: 'Welches Tier ist nach Gewicht das größte der Welt?', antworten: ['der Elefant', 'der Pottwal', 'der Blauwal', 'das Nashorn'], richtig: 2 },
  { id: 'q096', frage: 'Welcher Bildhauer schuf die Statue \'David\' in Florenz?', antworten: ['Donatello', 'Bernini', 'Leonardo da Vinci', 'Michelangelo'], richtig: 3 },
  { id: 'q097', frage: 'In welchem Land liegt die Stadt Marrakesch?', antworten: ['Marokko', 'Ägypten', 'Tunesien', 'Algerien'], richtig: 0 },
  { id: 'q098', frage: 'Welches Volk baute die Stadt Machu Picchu?', antworten: ['die Maya', 'die Inka', 'die Azteken', 'die Olmeken'], richtig: 1 },
  { id: 'q099', frage: 'Wie viele Zähne hat ein erwachsener Mensch normalerweise?', antworten: ['28', '30', '32', '34'], richtig: 2 },
  { id: 'q100', frage: 'In welcher Sportart gibt es den Kampfrichter-Ruf \'Ippon\'?', antworten: ['Fechten', 'Taekwondo', 'Ringen', 'Judo'], richtig: 3 },
  { id: 'q101', frage: 'Welches Blechblasinstrument ist das kleinste und höchste?', antworten: ['die Trompete', 'die Posaune', 'die Tuba', 'das Horn'], richtig: 0 },
  { id: 'q102', frage: 'In welcher Stadt lebt die Zeichentrickfamilie Simpson?', antworten: ['Quahog', 'Springfield', 'South Park', 'Bedrock'], richtig: 1 },
  { id: 'q103', frage: 'Welcher Detektiv wurde von Arthur Conan Doyle erschaffen?', antworten: ['Hercule Poirot', 'Miss Marple', 'Sherlock Holmes', 'Philip Marlowe'], richtig: 2 },
  { id: 'q104', frage: 'Welche Milch wird für echten Mozzarella di Bufala verwendet?', antworten: ['Kuhmilch', 'Ziegenmilch', 'Schafmilch', 'Büffelmilch'], richtig: 3 },
  { id: 'q105', frage: 'Wie nennt man die Lehre von der Bedeutung der Wörter?', antworten: ['Semantik', 'Syntax', 'Phonetik', 'Morphologie'], richtig: 0 },
  { id: 'q106', frage: 'Was ist die Hauptaufgabe eines Prozessors (CPU) im Computer?', antworten: ['Daten dauerhaft speichern', 'Berechnungen ausführen', 'Bilder anzeigen', 'Strom liefern'], richtig: 1 },
  { id: 'q107', frage: 'Welches Meerestier kann sich durch Farbwechsel perfekt tarnen?', antworten: ['der Delfin', 'der Hai', 'der Oktopus', 'der Thunfisch'], richtig: 2 },
  { id: 'q108', frage: 'Wer malte \'Das Mädchen mit dem Perlenohrring\'?', antworten: ['Rembrandt', 'Vincent van Gogh', 'Pieter Bruegel', 'Johannes Vermeer'], richtig: 3 },
  { id: 'q109', frage: 'Welches Meer liegt zwischen Europa und Nordafrika?', antworten: ['das Mittelmeer', 'das Rote Meer', 'das Schwarze Meer', 'die Nordsee'], richtig: 0 },
  { id: 'q110', frage: 'Wer verfasste maßgeblich die Unabhängigkeitserklärung der USA?', antworten: ['George Washington', 'Thomas Jefferson', 'Benjamin Franklin', 'John Adams'], richtig: 1 },
  { id: 'q111', frage: 'Welche Kraft hält die Planeten auf ihrer Bahn um die Sonne?', antworten: ['der Magnetismus', 'die Reibung', 'die Gravitation', 'die Fliehkraft'], richtig: 2 },
  { id: 'q112', frage: 'Wie viele Spieler hat eine Basketballmannschaft auf dem Feld?', antworten: ['6', '7', '4', '5'], richtig: 3 },
  { id: 'q113', frage: 'Wie nennt man eine Gruppe von vier Musikern?', antworten: ['Quartett', 'Trio', 'Quintett', 'Duett'], richtig: 0 },
  { id: 'q114', frage: 'Wer spielte den Joker in \'The Dark Knight\' von 2008?', antworten: ['Jack Nicholson', 'Heath Ledger', 'Joaquin Phoenix', 'Jared Leto'], richtig: 1 },
  { id: 'q115', frage: 'Wer schrieb den Roman \'Die Buddenbrooks\'?', antworten: ['Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Günter Grass'], richtig: 2 },
  { id: 'q116', frage: 'Was bedeutet \'al dente\' bei gekochten Nudeln?', antworten: ['sehr weich gekocht', 'roh', 'überkocht', 'bissfest gekocht'], richtig: 3 },
  { id: 'q117', frage: 'Welches Wort ist ein Synonym für \'schnell\'?', antworten: ['flink', 'träge', 'langsam', 'müde'], richtig: 0 },
  { id: 'q118', frage: 'Welches Unternehmen brachte das erste iPhone auf den Markt?', antworten: ['Samsung', 'Apple', 'Nokia', 'Sony'], richtig: 1 },
  { id: 'q119', frage: 'Welcher heute lebende Vogel legt die größten Eier?', antworten: ['der Adler', 'der Pinguin', 'der Strauß', 'der Kondor'], richtig: 2 },
  { id: 'q120', frage: 'Welche Kunstepoche war stark von Licht- und Farbeindrücken geprägt (Monet, Renoir)?', antworten: ['Expressionismus', 'Realismus', 'Barock', 'Impressionismus'], richtig: 3 },
  { id: 'q121', frage: 'Wie viele Bundesländer hat Deutschland?', antworten: ['16', '13', '14', '18'], richtig: 0 },
  { id: 'q122', frage: 'In welchem Jahr endete der Zweite Weltkrieg in Europa?', antworten: ['1943', '1945', '1944', '1946'], richtig: 1 },
  { id: 'q123', frage: 'Was misst man mit einem Barometer?', antworten: ['die Temperatur', 'die Luftfeuchtigkeit', 'den Luftdruck', 'die Windgeschwindigkeit'], richtig: 2 },
  { id: 'q124', frage: 'Was bedeutet die Rote Karte im Fußball?', antworten: ['Verwarnung', 'Elfmeter', 'Auszeit', 'Platzverweis'], richtig: 3 },
  { id: 'q125', frage: 'Aus welchem Land stammt der Wiener Walzer ursprünglich?', antworten: ['Österreich', 'Deutschland', 'Ungarn', 'die Schweiz'], richtig: 0 },
  { id: 'q126', frage: 'Welche Automarke fährt James Bond in vielen Filmen bevorzugt?', antworten: ['Jaguar', 'Aston Martin', 'Ferrari', 'Porsche'], richtig: 1 },
  { id: 'q127', frage: 'Welche Nuss steckt klassisch in Pesto Genovese?', antworten: ['Walnüsse', 'Mandeln', 'Pinienkerne', 'Haselnüsse'], richtig: 2 },
  { id: 'q128', frage: 'Wie viele Bit ergeben ein Byte?', antworten: ['4', '16', '10', '8'], richtig: 3 },
  { id: 'q129', frage: 'Wie nennt man ein weibliches Pferd?', antworten: ['Stute', 'Fohlen', 'Hengst', 'Wallach'], richtig: 0 },
  { id: 'q130', frage: 'Wie heißt die Hauptstadt von Japan?', antworten: ['Osaka', 'Tokio', 'Kyoto', 'Yokohama'], richtig: 1 },
  { id: 'q131', frage: 'Welches Bauwerk in China wurde zum Schutz vor Invasionen errichtet?', antworten: ['der Sommerpalast', 'die Verbotene Stadt', 'die Chinesische Mauer', 'der Tempel des Himmels'], richtig: 2 },
  { id: 'q132', frage: 'Welches Element hat die Ordnungszahl 1 im Periodensystem?', antworten: ['Helium', 'Sauerstoff', 'Kohlenstoff', 'Wasserstoff'], richtig: 3 },
  { id: 'q133', frage: 'In welcher Wintersportart nennt man die Abfahrtsstrecke \'Piste\'?', antworten: ['Skifahren', 'Eishockey', 'Rodeln', 'Biathlon'], richtig: 0 },
  { id: 'q134', frage: 'Wie heißt Harrys bester Freund in \'Harry Potter\'?', antworten: ['Neville Longbottom', 'Ron Weasley', 'Draco Malfoy', 'Seamus Finnigan'], richtig: 1 },
  { id: 'q135', frage: 'Woraus wird traditioneller Balsamico-Essig hergestellt?', antworten: ['Apfelwein', 'Malzessig', 'Traubenmost', 'Reiswein'], richtig: 2 },
  { id: 'q136', frage: 'Welches Tier wird umgangssprachlich als \'Wüstenschiff\' bezeichnet?', antworten: ['der Esel', 'das Zebra', 'das Lama', 'das Kamel'], richtig: 3 },
  { id: 'q137', frage: 'Welche Wüste in Asien ist eine der größten der Welt?', antworten: ['die Gobi', 'die Sahara', 'die Kalahari', 'die Atacama'], richtig: 0 },
  { id: 'q138', frage: 'Wie nennt man den direkten Übergang von fest zu gasförmig?', antworten: ['Kondensation', 'Sublimation', 'Verdunstung', 'Erstarrung'], richtig: 1 },
  { id: 'q139', frage: 'Welches Land besteht aus mehr als 17.000 Inseln?', antworten: ['die Philippinen', 'Malaysia', 'Indonesien', 'Japan'], richtig: 2 },
  { id: 'q140', frage: 'Wie viele Kammern hat ein menschliches Herz?', antworten: ['2', '3', '5', '4'], richtig: 3 },
];
