/**
 * Fragen fuer "Wer würde eher".
 *
 * Alle stimmen gleichzeitig fuer eine Person aus der Runde ab; wer Stimmen
 * bekommt, trinkt je Stimme einen Schluck. Die Fragen zielen deshalb auf
 * Verhalten, das man konkreten Mitspielern zutraut, ohne jemanden wirklich
 * blosszustellen.
 *
 * Neue Eintraege werden hinten angehaengt, mit der naechsten freien
 * Kennung. Bestehende Kennungen aendern sich nie, auch nicht beim Umsortieren.
 */
import type { Spruch } from './typen.js';

export const WER_EHER_SPRUECHE: readonly Spruch[] = [
  { id: 'w001', text: 'Wer würde eher den Flug verpassen, weil er noch schnell duschen wollte?' },
  { id: 'w002', text: 'Wer würde eher aus Versehen die Gruppe im falschen Chat anschreiben?' },
  { id: 'w003', text: 'Wer würde eher auf einer Party als Erster die Tanzfläche eröffnen?' },
  { id: 'w004', text: 'Wer würde eher beim Kochen den Rauchmelder aktivieren?' },
  { id: 'w005', text: 'Wer würde eher im falschen Meeting landen und das erst nach Minuten merken?' },
  { id: 'w006', text: 'Wer würde eher auf einem Roadtrip die Karte verkehrt herum halten?' },
  { id: 'w007', text: 'Wer würde eher nachts um zwei noch Essen bestellen, obwohl morgen früh ein Termin wartet?' },
  { id: 'w008', text: 'Wer würde eher auf jedem Foto die Augen geschlossen haben?' },
  { id: 'w009', text: 'Wer würde eher auf einer Wanderung behaupten, den Weg zu kennen, und sich dann verlaufen?' },
  { id: 'w010', text: 'Wer würde eher im Vorstellungsgespräch vergessen, das Handy auf lautlos zu stellen?' },
  { id: 'w011', text: 'Wer würde eher als Erster auf einer Feier einschlafen?' },
  { id: 'w012', text: 'Wer würde eher beim Karaoke das Mikro nicht mehr abgeben wollen?' },
  { id: 'w013', text: 'Wer würde eher versuchen, einen ganzen Umzug an einem Nachmittag zu schaffen?' },
  { id: 'w014', text: 'Wer würde eher beim Kartenspiel am offensichtlichsten schummeln?' },
  { id: 'w015', text: 'Wer würde eher eine private Nachricht aus Versehen öffentlich posten?' },
  { id: 'w016', text: 'Wer würde eher bei einer Wette hinterher die Regeln neu auslegen?' },
  { id: 'w017', text: 'Wer würde eher beim Grillen alles anbrennen lassen und trotzdem "perfekt" behaupten?' },
  { id: 'w018', text: 'Wer würde eher morgens versehentlich die falsche Zahnbürste benutzen?' },
  { id: 'w019', text: 'Wer würde eher auf einem Konzert lauter singen als die Band selbst?' },
  { id: 'w020', text: 'Wer würde eher bei einem Umzug den schwersten Karton für "ganz leicht" erklären?' },
  { id: 'w021', text: 'Wer würde eher nach zwei Serienfolgen auf dem Sofa einschlafen?' },
  { id: 'w022', text: 'Wer würde eher versuchen, sich mit einer faulen Ausrede an der Schlange vorbeizumogeln?' },
  { id: 'w023', text: 'Wer würde eher bei einer Schnitzeljagd als Letzter aufgeben?' },
  { id: 'w024', text: 'Wer würde eher auf einer Grillparty heimlich das letzte Stück Fleisch klauen?' },
  { id: 'w025', text: 'Wer würde eher bei einem Spieleabend die Regeln mitten im Spiel umschreiben?' },
  { id: 'w026', text: 'Wer würde eher im Gruppenchat den falschen Namen in eine Nachricht schreiben?' },
  { id: 'w027', text: 'Wer würde eher bis zur letzten Minute nach dem eigenen Reisepass suchen?' },
  { id: 'w028', text: 'Wer würde eher bei einem Vortrag die Folien in der falschen Reihenfolge zeigen?' },
  { id: 'w029', text: 'Wer würde eher beim Camping das Zelt verkehrt herum aufbauen?' },
  { id: 'w030', text: 'Wer würde eher ein Möbelstück ganz ohne Anleitung zusammenbauen wollen?' },
  { id: 'w031', text: 'Wer würde eher bei einem Quiz die einfachste Frage falsch beantworten?' },
  { id: 'w032', text: 'Wer würde eher auf einer langen Autofahrt als Erster wegdösen?' },
  { id: 'w033', text: 'Wer würde eher versuchen, mit einem einzigen kleinen Koffer drei Wochen zu reisen?' },
  { id: 'w034', text: 'Wer würde eher an Silvester das Feuerwerk zu früh anzünden?' },
  { id: 'w035', text: 'Wer würde eher bei einer Umfrage in der Runde als Letzter antworten?' },
  { id: 'w036', text: 'Wer würde eher aus Versehen ein Selfie mit dem Handy eines anderen machen?' },
  { id: 'w037', text: 'Wer würde eher auf einer Party heimlich die Musik umstellen?' },
  { id: 'w038', text: 'Wer würde eher in einem Escape Room den entscheidenden Hinweis übersehen?' },
  { id: 'w039', text: 'Wer würde eher live eine Ausrede für Zuspätkommen erfinden?' },
  { id: 'w040', text: 'Wer würde eher bei einem Brettspiel am längsten über einen einzigen Zug nachdenken?' },
  { id: 'w041', text: 'Wer würde eher ein Gerücht in der Gruppe als Erster weiterverbreiten?' },
  { id: 'w042', text: 'Wer würde eher auf einer Party wildfremde Leute in ein Gespräch ziehen?' },
  { id: 'w043', text: 'Wer würde eher beim Umzug die falschen Kartons als Erstes auspacken?' },
  { id: 'w044', text: 'Wer würde eher versuchen, dort einzuparken, wo eigentlich kein Platz mehr ist?' },
  { id: 'w045', text: 'Wer würde eher als Erster wieder aus dem kalten See rennen?' },
  { id: 'w046', text: 'Wer würde eher versuchen, ein ganzes Buffet im Alleingang zu testen?' },
  { id: 'w047', text: 'Wer würde eher während des ganzen Films durchgehend kommentieren?' },
  { id: 'w048', text: 'Wer würde eher aus Versehen zwei Verabredungen auf denselben Abend legen?' },
  { id: 'w049', text: 'Wer würde eher die Trinkflasche ausgerechnet auf der Wanderung vergessen?' },
  { id: 'w050', text: 'Wer würde eher bei einem Ausflug die Richtung vorgeben und komplett falsch liegen?' },
  { id: 'w051', text: 'Wer würde eher mit dem Rad eine "Abkürzung" nehmen und sich dabei verfahren?' },
  { id: 'w052', text: 'Wer würde eher auf einer Feier die Musik am lautesten aufdrehen?' },
  { id: 'w053', text: 'Wer würde eher jedem im Raum einen Spitznamen geben, ob er will oder nicht?' },
  { id: 'w054', text: 'Wer würde eher bei einem Wettessen als Erster die Gabel hinlegen?' },
  { id: 'w055', text: 'Wer würde eher ein Meeting mit einem richtig schlechten Wortspiel eröffnen?' },
  { id: 'w056', text: 'Wer würde eher den Fotoapparat ausgerechnet am Ausflugstag zu Hause vergessen?' },
  { id: 'w057', text: 'Wer würde eher einen Marathon ohne ein einziges Training antreten?' },
  { id: 'w058', text: 'Wer würde eher als Erster auf der Tanzfläche stehen?' },
  { id: 'w059', text: 'Wer würde eher bei einem Rätsel einfach raten, statt nachzudenken?' },
  { id: 'w060', text: 'Wer würde eher vom Kurztrip den halben ungenutzten Koffer wieder mit nach Hause bringen?' },
  { id: 'w061', text: 'Wer würde eher jemanden mit einem richtig schlechten Kalauer aufheitern wollen?' },
  { id: 'w062', text: 'Wer würde eher in einer Diskussion am längsten auf seiner Meinung bestehen?' },
  { id: 'w063', text: 'Wer würde eher ein Zelt mitten im Regen aufbauen, statt auf besseres Wetter zu warten?' },
  { id: 'w064', text: 'Wer würde eher bei einem Spaziergang die geplante Strecke einfach verdoppeln?' },
  { id: 'w065', text: 'Wer würde eher mit einer improvisierten Rede alle im Raum überraschen?' },
  { id: 'w066', text: 'Wer würde eher bei einer Autopanne als Erster den Pannendienst rufen?' },
  { id: 'w067', text: 'Wer würde eher versuchen, einen Kuchen komplett ohne Rezept nachzubacken?' },
  { id: 'w068', text: 'Wer würde eher nach einem Umzug vergessen, wo die Kaffeemaschine gelandet ist?' },
  { id: 'w069', text: 'Wer würde eher am Bahnhof den letzten Anschlusszug in letzter Sekunde erreichen?' },
  { id: 'w070', text: 'Wer würde eher das Geschenkpapier lauter zerreißen als alle anderen zusammen?' },
  { id: 'w071', text: 'Wer würde eher mitten im Videocall den Hintergrund wechseln, ohne es zu merken?' },
  { id: 'w072', text: 'Wer würde eher bei einem Spieleabend am Ende allen die Regeln neu erklären wollen?' },
  { id: 'w073', text: 'Wer würde eher bei einem Kartenspiel mit einem Bluff durchkommen?' },
  { id: 'w074', text: 'Wer würde eher beim Grillfest das Steak ständig wenden, statt es liegen zu lassen?' },
  { id: 'w075', text: 'Wer würde eher einen freien Tag komplett verplanen, statt einfach nichts zu tun?' },
  { id: 'w076', text: 'Wer würde eher auf einer Wanderung die Karte verkehrt herum halten?' },
  { id: 'w077', text: 'Wer würde eher spontan vor allen ein Instrument ausprobieren wollen?' },
  { id: 'w078', text: 'Wer würde eher am längsten für ein einziges Gruppenfoto posieren?' },
  { id: 'w079', text: 'Wer würde eher mit einem Trick versuchen, die letzte Portion Nachtisch zu sichern?' },
  { id: 'w080', text: 'Wer würde eher versehentlich die falsche Jacke von einer Party mit nach Hause nehmen?' },
  { id: 'w081', text: 'Wer würde eher ein Rennen ernst nehmen, das eigentlich niemand ernst gemeint hat?' },
  { id: 'w082', text: 'Wer würde eher mitten im Telefonat aus Versehen auflegen und gleich zurückrufen?' },
  { id: 'w083', text: 'Wer würde eher versuchen, den Fernseher mit einem uralten Trick zu reparieren?' },
  { id: 'w084', text: 'Wer würde eher beim Umtrunk aus dem falschen Glas weitertrinken, ohne es zu merken?' },
  { id: 'w085', text: 'Wer würde eher sich an einem kniffligen Rätsel die ganze Nacht festbeißen?' },
  { id: 'w086', text: 'Wer würde eher das letzte Stück Kuchen heimlich verschwinden lassen?' },
  { id: 'w087', text: 'Wer würde eher mit einem Umweg fest davon überzeugt sein, schneller anzukommen?' },
  { id: 'w088', text: 'Wer würde eher bei einem Spieleabend als Erster die eigenen Regeln vergessen?' },
  { id: 'w089', text: 'Wer würde eher sich für eine Verspätung eine besonders kreative Ausrede ausdenken?' },
  { id: 'w090', text: 'Wer würde eher bei einer Wanderung freiwillig das schwerste Gepäck übernehmen?' },
  { id: 'w091', text: 'Wer würde eher ein einziges Foto so lange bearbeiten, bis es perfekt aussieht?' },
  { id: 'w092', text: 'Wer würde eher das Wetter für einen Ausflug komplett falsch einschätzen?' },
  { id: 'w093', text: 'Wer würde eher mit einem improvisierten Plan B die ganze Gruppe retten?' },
  { id: 'w094', text: 'Wer würde eher die Playlist auf einer Feier heimlich um eigene Lieder erweitern?' },
  { id: 'w095', text: 'Wer würde eher ein Gespräch mit einer völlig unpassenden Anekdote eröffnen?' },
  { id: 'w096', text: 'Wer würde eher bei einem Spaziergang plötzlich einen ganz neuen Weg vorschlagen?' },
  { id: 'w097', text: 'Wer würde eher mit einem Mitternachtssnack die ganze Küche wach halten?' },
  { id: 'w098', text: 'Wer würde eher als Erster die Kerzen auf einem fremden Kuchen ausblasen wollen?' },
  { id: 'w099', text: 'Wer würde eher ein Projekt noch in der letzten Nacht vor der Deadline retten?' },
  { id: 'w100', text: 'Wer würde eher beim Fotoshooting am längsten nach der perfekten Pose suchen?' },
  { id: 'w101', text: 'Wer würde eher bekifft die Pizza bestellen und die Adresse falsch angeben?' },
  { id: 'w102', text: 'Wer würde eher bekifft eine halbe Stunde über eine Wolke reden?' },
  { id: 'w103', text: 'Wer würde eher beim Drehen so lange brauchen, dass alle anderen schon fertig sind?' },
  { id: 'w104', text: 'Wer würde eher bekifft behaupten, er sei überhaupt nicht bekifft?' },
  { id: 'w105', text: 'Wer würde eher bekifft den ganzen Snackvorrat der Gruppe allein wegessen?' },
  { id: 'w106', text: 'Wer würde eher bekifft eine Diskussion anfangen, an die sich am nächsten Tag niemand erinnert?' },
  { id: 'w107', text: 'Wer würde eher bekifft die Musik aussuchen und dabei nie über den ersten Song hinauskommen?' },
  { id: 'w108', text: 'Wer würde eher bekifft mitten im Satz vergessen, was er sagen wollte?' },
];
